### ISSUE TITLE
Python implementation?

### ISSUE THREAD

**Issue by eprparadocs** [yshavit/antlr-denter#13]
Thanks for a great library - highly useful. Any chance for a python implementation?

**Comment by yshavit** [comment]
I'm glad you find it useful!

A python implementation would have to be a totally different implementation, with nothing shared except the concept and _maybe_ some test cases, though even that would take refactoring of this code. In other words, it would really be a different project, not a variant of this one.

I don't really use python antlr, so I don't have the time/interest in writing such a thing, sorry!
