### ISSUE TITLE
Req: Make a NuGet package.

### ISSUE THREAD

**Issue by obiwanjacobi** [yshavit/antlr-denter#24]
For easier use in a project.

(it's just filling out some additional info the project properties in VS)

**Comment by yshavit** [comment]
Hi there! I'm not really familiar with NuGet, or even .NET in general tbh. But I welcome PRs, if you know how to do it. :-)

@K2017 provided the .NET port. I actually wonder if it (and the Python port) should get spun off to separate repos.

**Comment by obiwanjacobi** [comment]
It isn't that hard ;-)
https://learn.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio

I am sure you'll manage.

**Comment by rooney** [comment]
Oh wow the audacity
