### ISSUE TITLE
How to integrate with project?

### ISSUE THREAD

**Issue by Linchy** [yshavit/antlr-denter#8]
Hi I am new to netbeans, maven, and antlr.

Having just got to grips with installing the jdk, netbeans and the antlrworks2 plugin (and having 'interpret parser' actually work after fixing a file encoding issue), I am now not sure how to integrate your denter project.

Steps I tried (please correct where wrong):

(on Windows 7)
1. Download antlr-denter-master.zip to `\Downloads\` folder and unzip
2. Download maven to `\Downloads\` folder and unzip
3. Open command prompt in `"\Downloads\antlr-denter-master\antlr-denter-master\"` folder
4. Run command > `"..\..\apache-maven-3.2.5-bin\apache-maven-3.2.5\bin\mvn" install`
5. Got problem with `JAVA_HOME` not set so set that to `"C:\Progra~1\Java\jdk1.8.0_31"`
6. Run maven command again and it seemed to build everything
7. copied the `"\Downloads\antlr-denter-master\antlr-denter-master\core\target\antlr-denter-1.2-SNAPSHOT.jar"` into my java project and it was picked up by NetBeans:
![image](https://cloud.githubusercontent.com/assets/1840551/5887471/35685342-a3ca-11e4-8a8e-845eed1022e8.png)
8. Copied in your code for the lexer
9. Tried to run the 'Interpret Parser' but got an error 'An error occurred while constructing a lexer or parser ATN from the grammar'

No doubt I went wrong somewhere, but java/maven/cmdline aren't things I use regularly so any help would be appreciated.

**Comment by yshavit** [comment]
Hi Linchy, sorry for my delay. Did you figure this out? I'm not familiar with NetBeans.

**Comment by Linchy** [comment]
No I've been using a workaround for the moment. Could you give me a step by step then how you would integrate it into the IDE that you use (eclipse?). I'm sure the process wouldn't be too different.

**Comment by yshavit** [comment]
I just have a maven project with antlr-denter as a dependency (see example at https://github.com/yshavit/antlr-denter/blob/master/examples/pom.xml#L89-L93), and my IDE (Intellij IDEA) just picked it up. I'm not quite sure what's not working with your setup.
